### ISSUE TITLE
UnboundLocalError on start attempt

### ISSUE THREAD

**Issue by xobotyi** [Cristishor201/RailNationBot#27]
Attempt to run the pot is failing with error.

OS: Windows 10 x64
Python: Python 3.8.5
Browser: Chrome 84.0.4147.105

```
PS C:\RailNationBot-master\code> py .\install.py
Requirement already satisfied: pyautogui in c:\python38\lib\site-packages (0.9.50)
Requirement already satisfied: pymsgbox in c:\python38\lib\site-packages (from pyautogui) (1.0.8)
Requirement already satisfied: PyTweening>=1.0.1 in c:\python38\lib\site-packages (from pyautogui) (1.0.3)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\python38\lib\site-packages (from pyautogui) (0.1.26)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\python38\lib\site-packages (from pyautogui) (0.0.8)
Requirement already satisfied: mouseinfo in c:\python38\lib\site-packages (from pyautogui) (0.1.3)
Requirement already satisfied: Pillow>=6.2.1 in c:\python38\lib\site-packages (from pyscreeze>=0.1.21->pyautogui) (7.2.0)
Requirement already satisfied: pyrect in c:\python38\lib\site-packages (from pygetwindow>=0.0.5->pyautogui) (0.1.4)
Requirement already satisfied: pyperclip in c:\python38\lib\site-packages (from mouseinfo->pyautogui) (1.8.0)
Requirement already satisfied: opencv-python in c:\python38\lib\site-packages (4.3.0.36)
Requirement already satisfied: numpy>=1.17.3 in c:\python38\lib\site-packages (from opencv-python) (1.19.1)
Requirement already satisfied: numpy in c:\python38\lib\site-packages (1.19.1)
Requirement already satisfied: pynput in c:\python38\lib\site-packages (1.6.8)
Requirement already satisfied: six in c:\python38\lib\site-packages (from pynput) (1.15.0)
PS C:\RailNationBot-master\code> py .\railBonuses.py
Program started at 00-14
Traceback (most recent call last):
  File ".\railBonuses.py", line 22, in <module>
    env.init(Resolution, Language)
  File "C:\RailNationBot-master\code\resources\env.py", line 45, in init
    name_images = lang.lang(Language)
  File "C:\RailNationBot-master\code\lang\lang.py", line 13, in lang
    return [assoc_1, assoc_2, continue_last, bonus_cant_already, lotery_free, lotery_bonus, bonus_you, video_present, secure_bonus, skip_buy_ticket, bonus_money, bonus_prestige, sudenly_error]
UnboundLocalError: local variable 'bonus_cant_already' referenced before assignment
```

**Comment by xobotyi** [comment]
Sorry this one is caused by attempt to set language to `ru`

**Comment by Cristishor201** [comment]
ru is not suported ... yet.

**Comment by xobotyi** [comment]
yeah ive got it. but tha main thing here that i cant get it working even with EN locale

**Comment by Cristishor201** [comment]
need some images from in-game. So please give me an invitation in an assoc. I am bad at russian language. :D

**Comment by Cristishor201** [comment]
> yeah ive got it. but tha main thing here that i cant get it working even with EN locale

it's about the other issue ?

**Comment by xobotyi** [comment]
@Cristishor201 i can provide you with screenshots both in eng and russian

**Comment by Cristishor201** [comment]
that's even way better ;)

**Comment by xobotyi** [comment]
> > yeah ive got it. but tha main thing here that i cant get it working even with EN locale
> 
> it's about the other issue ?

no, its simply not working.
bot opens the associacion widget, movin cursor to the wighet header, moves cursor horizontally and falls asleep, really weird

**Comment by xobotyi** [comment]
[screenshots russian.zip](https://github.com/Cristishor201/RailNationBot/files/5077587/screenshots.russian.zip)
here are russian screenshots

**Comment by xobotyi** [comment]
@Cristishor201 [screenshots en.zip](https://github.com/Cristishor201/RailNationBot/files/5077616/screenshots.en.zip)
And here are English (UK) as it is shown to me
