### ISSUE TITLE
TypeError  on start attempt

### ISSUE THREAD

**Issue by xobotyi** [Cristishor201/RailNationBot#28]
Attempt to run the bot is failing with error.

OS: Windows 10 x64
Python: Python 3.8.5
Browser: Chrome 84.0.4147.105

```
PS C:\RailNationBot-2.0\code> py .\install.py
Requirement already satisfied: pyautogui in c:\python38\lib\site-packages (0.9.50)
Requirement already satisfied: pymsgbox in c:\python38\lib\site-packages (from pyautogui) (1.0.8)
Requirement already satisfied: PyTweening>=1.0.1 in c:\python38\lib\site-packages (from pyautogui) (1.0.3)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\python38\lib\site-packages (from pyautogui) (0.1.26)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\python38\lib\site-packages (from pyautogui) (0.0.8)
Requirement already satisfied: mouseinfo in c:\python38\lib\site-packages (from pyautogui) (0.1.3)
Requirement already satisfied: Pillow>=6.2.1 in c:\python38\lib\site-packages (from pyscreeze>=0.1.21->pyautogui) (7.2.0)
Requirement already satisfied: pyrect in c:\python38\lib\site-packages (from pygetwindow>=0.0.5->pyautogui) (0.1.4)
Requirement already satisfied: pyperclip in c:\python38\lib\site-packages (from mouseinfo->pyautogui) (1.8.0)
Requirement already satisfied: opencv-python in c:\python38\lib\site-packages (4.3.0.36)
Requirement already satisfied: numpy>=1.17.3 in c:\python38\lib\site-packages (from opencv-python) (1.19.1)
Requirement already satisfied: numpy in c:\python38\lib\site-packages (1.19.1)
Requirement already satisfied: pynput in c:\python38\lib\site-packages (1.6.8)
Requirement already satisfied: six in c:\python38\lib\site-packages (from pynput) (1.15.0)
PS C:\RailNationBot-2.0\code> py .\railBonuses.py
Program started at 00-21
Traceback (most recent call last):
  File ".\railBonuses.py", line 23, in <module>
    env.update()
  File "C:\RailNationBot-2.0\code\resources\env.py", line 119, in update
    errors[0:] = update_ratio(errors)
  File "C:\RailNationBot-2.0\code\resources\env.py", line 102, in update_ratio
    return [int(val_list[0]*ratio[0]), int(val_list[1]*ratio[1])]
TypeError: 'function' object is not subscriptable

**Comment by xobotyi** [comment]
Manually fixed it by renaming `env.error()` -> `env.get_error()` cause old function name overlapped variable name

**Comment by Cristishor201** [comment]
the script was designed to work in **1920 x 1080** resolution.
I will look in it to see why that part is not working.

**Comment by Cristishor201** [comment]
For testing (for me):

- 4:3 aspect ratio resolutions: 640×480, 800×600, 960×720, 1024×768, 1280×960, 1400×1050, 1440×1080 , 1600×1200, 1856×1392, 1920×1440, and 2048×1536.
- 16:10 aspect ratio resolutions: – 1280×800, 1440×900, 1680×1050, 1920×1200 and 2560×1600.
- 16:9 aspect ratio resolutions: 1024×576, 1152×648, 1280×720, 1366×768, 1600×900, 1920×1080, 2560×1440 and 3840×2160.

**Comment by xobotyi** [comment]
i've been setting  1920×1200 in config file.
